GET http://localhost:8000/

###
GET http://localhost:8000/locations

###
GET http://localhost:8000/locations/10

###
POST http://localhost:8000/locations
Content-Type: application/json

{
    "latitude": -23.4,
    "longitude": 10.53
}

###
DELETE http://localhost:8000/locations/3
